# --- !Ups

create table unregistered_users (
  id       bigint generated by default as identity (start with 1) not null primary key,
  email    varchar(255) not null,
  password varchar(255) not null
);

create table users (
  id       bigint generated by default as identity (start with 1) not null primary key,
  email    varchar(255) not null,
  password varchar(255) not null
);

create table user_roles (
  user_id bigint references users (id),
  role varchar(255)
);


# --- !Downs

drop table unregistered_users;
drop table users;
drop table user_roles;